services:
  postgres:
    container_name: 'kitchen-genius-postgres'
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_DB=kitchen-genius-db'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - '5431:5432'
    networks:
      - kitchen-genius-network
  api:
    container_name: 'kitchen-genius-api'
    build: .
    restart: always
    working_dir: /kitchen-genius-api
    ports:
      - '8080:8080'
    command: gradlew bootRun
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
    depends_on:
      - postgres
    networks:
      - kitchen-genius-network
networks:
  kitchen-genius-network:
    driver: bridge